// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { existsSync } from "fs";
import { dirname, join } from "path";
import { fileURLToPath } from "url";
import { defineConfig } from "prisma/config";

const configDir = dirname(fileURLToPath(import.meta.url));
const envNextToThisFile = join(configDir, ".env");
const envInCwd = join(process.cwd(), ".env");
config({
  path: existsSync(envNextToThisFile)
    ? envNextToThisFile
    : existsSync(envInCwd)
      ? envInCwd
      : envNextToThisFile,
});

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
